### ISSUE TITLE
how does the abysstracker available api works?

### ISSUE THREAD

**Issue by Frefreak** [shivas/abyss-blackbox#7]
Hi,
when I'm playing with the code I find fitting manager can't seems to get my fit. I noticed that its failing on this abyss-tracker api `/api/private/fittings/abyss-tracker/available` with status code 424. I don't quite understand how to use this api and not able to find any info with regarding to that api online. Can you tell me how is it supposed to work?

Some context:
I'm trying to port some parts of abyss-blackbox to linux to make the basic functionality works. Currently it can generate .abyss files without problem but many UI functionality are missing (like currently I need to specify the abyss tiers etc in the setting json directly, and I don't think I need the overlay parts for now).

This is a run I uploaded just now: https://abyssal.space/telemetry/65578764b1c04a6b5b0a687c 

As you can see it just looks like any other runs uploaded under windows, except the fitting part (the webpage only missing the ship icon, but I can see the pb itself stores detailed fitting info, I would like to complement the last piece and then I think I can happily start to use it myself for a long time).

Thanks, and amazing work you have done BTW!

**Comment by shivas** [comment]
Abyss tracker imports are available only if a token of abyss tracker is linked to your account at https://abyssal.space site. 
There is reason why path of API has `private` in it :) So in general if you go to https://abyssal.space/settings and link your abysstracker API token - this endpoint will start working. You can also add fitting from your clipboard (if you manage to make it work on linux).

Feel free to ask questions here or on discord.

**Comment by shivas** [comment]
For fittings to work you can use this method: https://github.com/shivas/abyss-blackbox/blob/main/internal/fittings/pb/record.go#L50

then fill PB https://github.com/shivas/abyss-blackbox/blob/main/protobuf/abyssfile.proto#L28 if I recall correctly (out of my head) this map of [pilotName:Fit] Fit described here: https://github.com/shivas/abyss-blackbox/blob/main/protobuf/abyssfile.proto#L37

And it's basically populated from values received from validate endpoint. For source you can use string `manual`

**Comment by Frefreak** [comment]
Thank you for the info. I will have a try of the linked account approach. I also tried the manual way the other day (copy EFT from clipboard, then validating from abyssal tracker api) and it seems to work too, but I haven't had a full test run yet.

Sorry about the late response BTW (I missed the notification until now)
